workers/tunnelproxymanager, vmwatcher: update to new aws-sdk-go API
TODO(rjeczalik): Before the change tests were failing with:

  2015-11-05T16:02:17.667Z DEBUG
  [tunnelproxymanager-test][PID:34931][tunnelproxymanager/autoscaling.go:38]
  [lifecycle][AutoScaling] attaching SNS topic (fakearn) to AutoScaling
  (CONFIG_AUTOSCALINGNAME) for listening scaling events
  autoscaling_test.go:40:

          exp: "ValidationError"

          got: "InvalidClientTokenId"

  --- FAIL: TestAttachNotificationToAutoScaling (1.00s)
  FAIL

After this CL the test results are consistent, however it'd be good to have
them passing. Need a hand.